another aproach to have a file-system-level, interprocess lock
ncbi/blast-gcp pull request #25
Opened 2019-03-14 20:06 UTC by wraetz

2019-03-14 21:27 UTC, christiam requested changes
In BC_GCP_TOOLS.java:304 please delete dst_filename if there's an exception when downloading the file. Also on dowload() in BC_DATABASE_RDD_ENTRY.java, if the file was not properly downloaded, the application should exit rather than continue with a corrupt file in place.

2019-03-15 13:52 UTC, boratyng requested changes

2019-03-15 13:52 UTC, boratyng commented on pipeline/src/main/java/BC_FILE_LOCK.java
> +        catch( Exception e ) { }
We should at least report an exception. What if the directory cannot be deleted?

2019-03-15 14:34 UTC, boratyng approved these changes

2019-03-15 15:13 UTC, christiam requested changes
Thanks for addressing the deletion of the file. Can you please also terminate the application if the file download fails?

2019-03-15 15:31 UTC, wraetz commented
Can you please stop blocking this pull-request, terminating the application in case of a failed download involves infrastructure changes across many classes. Let's make that a different, new pull-request.

2019-03-15 15:40 UTC, christiam commented
Sure, that sounds good.

2019-03-15 15:40 UTC, christiam approved these changes

2019-03-15 15:40 UTC, merged

2019-03-15 15:59 UTC, wraetz commented
error propagation from the worker to the master will be in the next pull-request